cmd: enable large file support (#3040)
This is needed to use xfs.h on 32bit platforms:

/usr/include/xfs/xfs.h:53:12: error: size of array ‘xfs_assert_largefile’ is too large
 extern int xfs_assert_largefile[sizeof(off_t)-8];