spread: switch fedora-26-64 back to manual
We're seeing consistent failures when installing packages:

  quiet: dnf -y --refresh install curl dbus-x11 expect git golang jq mock redhat-lsb-core rpm-build xdg-user-dirs
  quiet: exit status 1. Output follows:
  Failed to set locale, defaulting to C
  Error: Failed to synchronize cache for repo 'updates'
  quiet: end of output.

Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>